### ISSUE TITLE
EX-0 yarn start gives error. Is this api still workig?

### ISSUE THREAD

**Issue by keerthankumar** [tradovate/example-api-js#9]
I see below error -

yarn run v1.22.22
$ webpack serve
ℹ ｢wds｣: Project is running at http://localhost:8080/
ℹ ｢wds｣: webpack output is served from /
ℹ ｢wds｣: Content not from webpack is served from /Users/keerthan/Downloads/example-api-js-main/tutorial/Access/EX-0-Access-Start/dist
Error: error:0308010C:digital envelope routines::unsupported
    at Hash (node:internal/crypto/hash:79:19)
    at Object.createHash (node:crypto:139:10)
    at BulkUpdateDecorator.hashFactory (/Users/keerthan/Downloads/example-api-js-main/tutorial/Access/EX-0-Access-Start/node_modules/webpack/lib/util/createHash.js:144:18)
    at BulkUpdateDecorator.update (/Users/keerthan/Downloads/example-api-js-main/tutorial/Access/EX-0-Access-Start/node_modules/webpack/lib/util/createHash.js:46:50)
    at OriginalSource.updateHash (/Users/keerthan/Downloads/example-api-js-main/tutorial/Access/EX-0-Access-Start/node_modules/webpack-sources/lib/OriginalSource.js:104:8)
    at NormalModule._initBuildHash (/Users/keerthan/Downloads/example-api-js-main/tutorial/Access/EX-0-Access-Start/node_modules/webpack/lib/NormalModule.js:853:17)
    at handleParseResult (/Users/keerthan/Downloads/example-api-js-main/tutorial/Access/EX-0-Access-Start/node_modules/webpack/lib/NormalModule.js:918:10)
    at /Users/keerthan/Downloads/example-api-js-main/tutorial/Access/EX-0-Access-Start/node_modules/webpack/lib/NormalModule.js:1009:4
    at processResult (/Users/keerthan/Downloads/example-api-js-main/tutorial/Access/EX-0-Access-Start/node_modules/webpack/lib/NormalModule.js:732:11)
    at /Users/keerthan/Downloads/example-api-js-main/tutorial/Access/EX-0-Access-Start/node_modules/webpack/lib/NormalModule.js:792:5
node:internal/crypto/hash:79
  this[kHandle] = new _Hash(algorithm, xofLen, algorithmId, getHashCache());
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at Hash (node:internal/crypto/hash:79:19)
    at Object.createHash (node:crypto:139:10)
    at BulkUpdateDecorator.hashFactory (/Users/keerthan/Downloads/example-api-js-main/tutorial/Access/EX-0-Access-Start/node_modules/webpack/lib/util/createHash.js:144:18)
    at BulkUpdateDecorator.update (/Users/keerthan/Downloads/example-api-js-main/tutorial/Access/EX-0-Access-Start/node_modules/webpack/lib/util/createHash.js:46:50)
    at OriginalSource.updateHash (/Users/keerthan/Downloads/example-api-js-main/tutorial/Access/EX-0-Access-Start/node_modules/webpack-sources/lib/OriginalSource.js:104:8)
    at NormalModule._initBuildHash (/Users/keerthan/Downloads/example-api-js-main/tutorial/Access/EX-0-Access-Start/node_modules/webpack/lib/NormalModule.js:853:17)
    at handleParseResult (/Users/keerthan/Downloads/example-api-js-main/tutorial/Access/EX-0-Access-Start/node_modules/webpack/lib/NormalModule.js:918:10)
    at /Users/keerthan/Downloads/example-api-js-main/tutorial/Access/EX-0-Access-Start/node_modules/webpack/lib/NormalModule.js:1009:4
    at processResult (/Users/keerthan/Downloads/example-api-js-main/tutorial/Access/EX-0-Access-Start/node_modules/webpack/lib/NormalModule.js:732:11)
    at /Users/keerthan/Downloads/example-api-js-main/tutorial/Access/EX-0-Access-Start/node_modules/webpack/lib/NormalModule.js:792:5 {
  opensslErrorStack: [
    'error:03000086:digital envelope routines::initialization error',
    'error:0308010C:digital envelope routines::unsupported'
  ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v22.3.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by suprsidr** [comment]
Try lower nodejs version.
